kumuluzee:
  name: notification-service
  version: 1.0.0-SNAPSHOT
  dev:
    scan-libraries:
      - notification-service-lib
      - rest-lib
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count, Content-Type"
  streaming:
    kafka:
      consumer:
        bootstrap-servers: localhost:9091
        group-id: group1
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  openapi-mp:
    enabled: true
    servers: http://localhost:8080
    ui:
      mapping: /openapi/ui
      enabled: true
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/notification-service-db
      disk-space-health-check:
        threshold: 100000000
        type: liveness
      kafka-health-check:
        bootstrap-servers: localhost:9091
        minimum-available-nodes: 1
        request-timeout-ms: 1000
  config:
    namespace: env/dev
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  datasources:
    - jndi-name: jdbc/notification-service-db
      connection-url: jdbc:postgresql://localhost:5432/notification-service
      username: postgres
      password: postgres
      pool:
        max-size: 20
  migrations:
    enabled: true
    liquibase:
      datasources:
        - jndi-name: jdbc/notification-service-db
          changelog: db/db.changelog-master.xml
          startup:
            dropAll: false
            update: true

mydnacodes:
  notifications:
    email:
      enabled: false
      from: not_set
      user: not_set
      pass: not_set
      host: not_set
      port: not_set
